# -*- coding: utf-8 -*-
"""codsoft_Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_66XQH0D8yKVwuy66SIeQn4IKxngTBr
"""

# Advanced Rule-Based Chatbot
def chatbot():
    import datetime

    print("Chatbot: Hello! Welcome to your personal assistant chatbot.")
    print("Chatbot: How can I assist you today? (Type 'exit' anytime to end the conversation.)")

    while True:
        # Take user input
        user_input = input("You: ").strip().lower()

        # Exit condition
        if user_input == "exit":
            print("Chatbot: Thank you for chatting with me. Remember, I’m always here if you need help. Goodbye!")
            break

        # Greeting Responses
        elif any(greet in user_input for greet in ["hello", "hi", "hey", "greetings"]):
            print("Chatbot: Hello! It’s great to connect with you. What would you like to know today?")

        # Asking for chatbot's identity
        elif "who are you" in user_input or "your name" in user_input:
            print("Chatbot: I’m your virtual assistant. You can call me 'Buddy'. I'm here to assist you with various tasks.")

        # Time and Date Information
        elif "time" in user_input or "current time" in user_input:
            current_time = datetime.datetime.now().strftime("%H:%M:%S")
            print(f"Chatbot: The current time is {current_time}.")
        elif "date" in user_input or "today's date" in user_input:
            today_date = datetime.datetime.now().strftime("%Y-%m-%d")
            print(f"Chatbot: Today's date is {today_date}.")

        # Weather Query
        elif "weather" in user_input:
            print("Chatbot: I can’t fetch real-time weather updates, but a quick search on your favorite weather app should help!")

        # Fun Facts
        elif "fun fact" in user_input or "interesting fact" in user_input:
            facts = [
                "The Eiffel Tower can be 15 cm taller during summer due to thermal expansion of metal.",
                "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
                "Octopuses have three hearts. Two pump blood to the gills, while the third pumps it to the rest of the body."
            ]
            from random import choice
            print(f"Chatbot: Here’s an interesting fact: {choice(facts)}")

        # Jokes
        elif "joke" in user_input or "make me laugh" in user_input:
            jokes = [
                "Why don’t scientists trust atoms? Because they make up everything!",
                "Why did the computer go to the doctor? Because it caught a virus!",
                "What do you call a fake noodle? An Impasta!"
            ]
            from random import choice
            print(f"Chatbot: Here’s a joke for you: {choice(jokes)}")

        # Feedback Collection
        elif "feedback" in user_input:
            print("Chatbot: I’d love to hear your feedback! What do you think about this chatbot?")
            feedback = input("You: ")
            print("Chatbot: Thank you for your feedback! I’ll use this to improve.")

        # Advice and Encouragement
        elif "advice" in user_input or "motivate me" in user_input:
            print("Chatbot: Here’s a piece of advice: Success doesn’t come from what you do occasionally. It comes from what you do consistently.")

        # Academic Assistance
        elif "math" in user_input or "calculate" in user_input:
            print("Chatbot: Sure, I can help with basic calculations! Type the expression (e.g., 2 + 2):")
            try:
                expression = input("You: ")
                result = eval(expression)
                print(f"Chatbot: The result is {result}.")
            except Exception as e:
                print("Chatbot: Oops! That didn’t seem like a valid math expression. Please try again.")

        # Personality Queries
        elif "how are you" in user_input:
            print("Chatbot: I’m doing great! Thanks for asking. How can I assist you today?")
        elif "what can you do" in user_input:
            print("Chatbot: I can chat with you, provide information, tell jokes, share fun facts, and even solve simple math problems!")

        # Compliments
        elif "thank you" in user_input or "thanks" in user_input:
            print("Chatbot: You’re most welcome! I’m glad I could help.")

        # Unrecognized Queries
        else:
            print("Chatbot: I’m sorry, I’m not sure how to respond to that. Could you try rephrasing your question?")
            print("Chatbot: (Hint: You can ask about time, date, jokes, or even fun facts!)")

# Run the chatbot
chatbot()